### ISSUE TITLE
Binary for macos-arm64

### ISSUE THREAD

**Issue by aka-Ani** [asg017/sqlite-html#14]
Awesome extension, thanks Alex. Not really an issue, but I was wondering if it was intentional not having macos-arm64 binaries in the releases. I was able to compile it with no issue but figured it could be handy for people who don't want to install the Go runtime.

**Comment by asg017** [comment]
Yeah, back when I first made this it was difficult/impossible to compile for Mac M1s on Github Actions, which is where the current macos-x86_64/linux/windows builds currently happen. 

Although since then the action runners have improved, and I now have a self-hosted Mac M1 runner at my disposal, so I'll try out adding Mac M1/M2 builds to sqlite-html!

Thanks for reporting

**Comment by aka-Ani** [comment]
Awesome! Thanks again for the useful extension :)

**Comment by asg017** [comment]
Hey @aka-Ani , there are now `macos-arm64` builds in recent version. Let me know if they don't work for you! https://github.com/asg017/sqlite-html/releases/tag/v0.1.2
